### ISSUE TITLE
Dry

### ISSUE THREAD

**Issue by mcphendriks** [moonlightlizaa/the-startup-responsive-interactieve-website#5]
https://github.com/moonlightlizaa/the-startup-responsive-interactieve-website/blob/659525be517d47f91c6698d1af8b4e6986d1c871/styles/style.css#L21

Ik zie dat je 2x dezelfde font-family gebruikt, maak gebruik custom properties, zodat je jezelf niet hoeft te herhalen.

**Comment by moonlightlizaa** [comment]
Dankjewel!
