### ISSUE TITLE
<h2> gebruik

### ISSUE THREAD

**Issue by MokhtarAkle** [moonlightlizaa/the-startup-responsive-interactieve-website#7]
https://github.com/moonlightlizaa/the-startup-responsive-interactieve-website/blob/659525be517d47f91c6698d1af8b4e6986d1c871/index.html#L38

Als je gebruik maakt van h1-h6 is het beter om deze exclusief voor headings te gebruiken. Als je tekst te lang ( denk meer dan 1 zin, meer dan 12 woorden, voel dit zelf aan) wordt is het beter om gebruik te maken van een andere tag zoals een <p>.

**Comment by moonlightlizaa** [comment]
Done :)
