### ISSUE TITLE
Dry

### ISSUE THREAD

**Issue by mcphendriks** [moonlightlizaa/the-startup-responsive-interactieve-website#8]
https://github.com/moonlightlizaa/the-startup-responsive-interactieve-website/blob/659525be517d47f91c6698d1af8b4e6986d1c871/styles/style.css#L58

De line-height gebruik je ook meerdere malen, deze kun je plaatsen in je root:

**Comment by moonlightlizaa** [comment]
Aangepast! Dankjewel! 💗
