### ISSUE TITLE
Fallback font

### ISSUE THREAD

**Issue by MokhtarAkle** [moonlightlizaa/the-startup-responsive-interactieve-website#9]
https://github.com/moonlightlizaa/the-startup-responsive-interactieve-website/blob/659525be517d47f91c6698d1af8b4e6986d1c871/styles/style.css#L31

Maak gebruik van een fallback font als je een font-family selecteert om mogelijke problemen te voorkomen als je primaire font-family niet ingeladen kan worden. https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/

**Comment by moonlightlizaa** [comment]
Wow bedankt voor de link met informatie! Ik heb het nu aangepast.
